apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: test
  labels:
    app: flask-app
    component: greeting
spec:
  selector:
    app: flask-app
    component: greeting
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP